### ISSUE TITLE
Pseudo proxy

### ISSUE THREAD

**Issue by cybertza** [Tertiush/ParadoxIP150v2#12]
Hi bud. Great work.
Busy with my selection of HomeAutomation platforms, keep sidestepping between Home Assistant on Open Hab.
Either way mqtt would be my way forward, great job.

So I was wondering about a pseudo proxy model workaround for the multiple connection limit of the ip150 that I read about.

Would it be possible to create a small proxy server to pretend to be the ip150.
So your mobile app/winload/babyware connects to it, and then it forwards towards the ip that you have a stable connection with.

In effect you are being a router and you Nat the one connection, allowing in effect both multiple connections to the ip150/panel, and still have the ability to parse data towards the mqtt stack.

It is just an idea, I see everyone is having a hard time with this.
It falls in the same front as automating a light, but now you loose your switch, and just ur phone controls it.

Lastly, something I will test as well, but I know when I connect the software to the panel my installer code stops working at the keypad. Will let u know if the software has the same effect.

Like I said Great job!

**Comment by Tertiush** [comment]
Hi, thanks for the comments.

Yes is this is an issue I know. Using a proxy will definitely work, but this might introduce even more issues as you have to proxy both the http/s port and the software port as they should stay "together" with the IPs.

I have an alternative proposal.... When someone tries to connect to the alarm panel whilst an existing connection is active, an event is sent to the already connected session. It contains two 16 byte payloads, the first I assume is some header, and the second I'm not too sure about but it loos like it contains the panel's pin (1234 in this case - I changed it for this post). The code can be extended to listen for this event. When it's received the script disconnects and wait for a minute or two then tries to reconnect (or just tries until it succeeds).

Here's the event (in hex):
aa 03 00 01 72 f6 00 00  00 ee ee ee ee ee ee ee 12 34 00 ee ee ee ee ee  ee ee ee ee ee ee ee ee

If I had time to code and debug this I would've already done it, but I simply don't have right now. Would you like to do it and submit a PR?

**Comment by Tertiush** [comment]
Detection of a 3rd party connection is now supported, therefore closing this issue
