### ISSUE TITLE
Abstract logic to support multiple communication channels (Serial, Modem, IP, etc...)

### ISSUE THREAD

**Issue by jpbarraca** [Tertiush/ParadoxIP150v2#16]
The discovery, control and publish logic can be abstracted from the IP150 module, to also consider other channels.

In [my fork](
https://github.com/jpbarraca/ParadoxIP150v2) I made this, with focus in the Serial interface. The IP150 channel is missing but can be added. Is there interest to evolve towards this direction?

**Comment by Tertiush** [comment]
although valuable, I do not have the time to pursue this. sorry
