### ISSUE TITLE
Support for SP4000

### ISSUE THREAD

**Issue by Tertiush** [Tertiush/ParadoxIP150v2#3]
Following from discussion with @andrewb-nz (issue #2)

**Comment by Tertiush** [comment]
@andrewb-nz

See the discussion going on here: https://github.com/Tertiush/ParadoxIP150v2/issues/4

Worth a shot on the SP4000.

**Comment by andrewb-nz** [comment]
Finally got time to look at this again, I resolved the Label read issue by setting the Panel ID/Pass to 0000 as discussed here [#8](https://github.com/Tertiush/ParadoxIP150v2/issues/8)

**Comment by Tertiush** [comment]
closing as the issue has been quiet for a while
