### ISSUE TITLE
PGM signal conflicts with remote

### ISSUE THREAD

**Issue by papaiatis** [Tertiush/ParadoxIP150v2#41]
Hi!

Using this software integrated into my Home Assistant I'm able to open or close the motorized fence, however when I do so the remote controllers does not work anymore. I have to shut down this software in order to make the remotes work again.

Does anyone else have this same problem? Is there any solution for it?

Thanks!

**Comment by psyciknz** [comment]
Hm. I’m not sure if it was this (or my fork) or the pai one from jbarraca,  but I did notice that.   It took a while for the control to come back to the remote.    Was worrying for a while.

**Comment by papaiatis** [comment]
So did you fix it in any way? Or is it still the same?

**Comment by psyciknz** [comment]
Fixed the code, or get the remote going again?

No, not fixed the code, not sure what's causing it, but the remote did come back to being usable after a time.  I even when into babyware to have a look if the config had changed, but couldn't see anything.

**Comment by papaiatis** [comment]
Alright. So it's still not working as it should.
I did try to fix the code but no luck so far.

**Comment by Tertiush** [comment]
The issue is that the current PGM commands are latched/override commands. Paradox also has a "Release" type command which I suspect does not latch the PGM. Go check out the "Monitoring -> PGM" tab in Winload. If someone has time they can confirm this, then we simply need to reverse engineer that command and add it to the list.

**Comment by psyciknz** [comment]
In the SPxx Programming guide it has:
0x30 = PGM ON in overwrite mode
0x31 = PGM OFF in overwrite mode
0x32 = PGM ON
0x33 = PGM OFF

And in the ParadoxMap.py, I see we're posting a 30 and 31.  Does that mean we should be using 32/33?

**Comment by papaiatis** [comment]
@psyciknz
Wow that worked! I replaced those values from 30/31 to 32/33 and the remote is now working again.

**Comment by psyciknz** [comment]
And you still have pgm control?  

Ok I might add that to my fork.  I’m not sure of the code bases are compatible any more.  I’ve had to rename the main ip150 script name for use in Travis and auto building in docker

**Comment by Tertiush** [comment]
That's great news thanks for letting us know! Please feel free to do a PR
to add this function, I think others will likely also use it.

**Comment by papaiatis** [comment]
@psyciknz 
We're also using a different fork that was meant to be used in Home Assistant (as a plugin), this one: [ParadoxIP150v2_Hassio](https://github.com/alexricher/ParadoxIP150v2_Hassio)
With this change you suggested we are now able to both control the garage door and motorized fence from Home Assistant using this script (PGM control) and control the same things with a physical remote control. 
The latter wasn't working after we did a PGM control from the script, and its probably because 0x30 and 0x31 are in overwrite mode.
Changing these to 0x32 and 0x33 both the script and the remote works in the same time in whatever order I use them.
