### ISSUE TITLE
IP150 V4.42 Login issue

### ISSUE THREAD

**Issue by yusufk** [Tertiush/ParadoxIP150v2#46]
Firmware version 4.42 seems to have changed the way login works. Now only asks for panel code. Something needs to be updated to fix login. Any idea how to find out what though?

**Comment by yusufk** [comment]
Damn. The password is now fixed to paradox, but that doesn't help, they've removed the status_page.html, so no info to scrape.

**Comment by yozik04** [comment]
I can only offer you PAI https://github.com/ParadoxAlarmInterface/pai
It does not use web interface to fetch data.

**Comment by yusufk** [comment]
User= "paradox" but there's no longer a status page to scrape.
