### ISSUE TITLE
Can I access the panel via http/IOS app when script running

### ISSUE THREAD

**Issue by psyciknz** [Tertiush/ParadoxIP150v2#9]
I've tried changing the poll_sleep etc, but when trying to connect to the http page I get the please wait message (as something else connected).

I assumed that with polling enabled, that the script would connect and disconnect as per the polling period.

**Comment by merlinmb** [comment]
I manually start the script, connecting to IP100 : fetched labels, gets a few events and then reports "Event:Special (Partition 1);SubEvent:Software log off".

Before this event is reported - I have no luck connecting with the official iOS paradox app (this is expected as I have never had success with multiple IP connections); post this event: I can log in again.

**Comment by psyciknz** [comment]
I never actually see it push that event.  It sits on State Machine: 4: listening for events
